### ISSUE TITLE
same script for setup and update?

### ISSUE THREAD

**Issue by karlpokus** [chrishunt/dot-files#10]
Hi!

Thanks for sharing your dotfiles. You have two files in `/scripts` but only refer to one of them in the readme. What gives?

**Comment by chrishunt** [comment]
`script/setup` is all a person needs to stay up-to-date with this repository.

`script/update` is something I run at random intervals on my machine to update the vim plugins in this repository. It's not something other people need to run because I'm already running it. 😃

**Comment by karlpokus** [comment]
👍
