### ISSUE TITLE
Can you include the .bash_profile please?

### ISSUE THREAD

**Issue by Graystripe17** [chrishunt/dot-files#11]
I noticed in your gitignore .bash_profile is missing. I accidentally deleted mine, can I see yours please?
Thanks!

**Comment by chrishunt** [comment]
Hi @Graystripe17. I'm not using a `.bash_profile`. My zsh configuration is in [`.zshrc`](https://github.com/chrishunt/dot-files/blob/master/.zshrc) and other configurations (like path and aliases) in [oh-my-zsh](https://github.com/chrishunt/oh-my-zsh/tree/master/custom).

**Comment by Graystripe17** [comment]
Thanks anyways. I ended up remaking my own: https://github.com/Graystripe17/dotVimShell
