### ISSUE TITLE
Slow scrolling in vim due to cursorline and relativenumber

### ISSUE THREAD

**Issue by whatyouhide** [chrishunt/dot-files#5]
Hello, sorry to bother you. I stole a couple of `vimrc` goodness from your dotfiles.

Since I use a very similar iTerm + tmux + vim configuration as yours, I was wondering if you're experiencing any scrolling slowdowns inside vim.
I found the `cursorline` and `relativenumber` options to noticeably slow down scrolling (even when used each separately).

I'm on MacVim 7.4 (which I installed via `brew install macvim`, as you did too I guess).

**Comment by Jaco-Pretorius** [comment]
I fixed this with `autocmd Filetype ruby setlocal nocursorline`

**Comment by swapkats** [comment]
@whatyouhide What terminal emulator do you use? If you use iterm you could check if your GPU is enabled. This gives a nice perfomance boost. Try **Help > GPU Renderer Availablity**
