### ISSUE TITLE
terminal color scheme?

### ISSUE THREAD

**Issue by johnrees** [chrishunt/dot-files#9]
I know I'm missing something really obvious but how do you update the color scheme to be consistent in the terminal i.e. the default is a white background, unless i am working in vim, thanks

![screen shot 2016-01-27 at 14 32 56](https://cloud.githubusercontent.com/assets/601961/12616401/def53862-c502-11e5-954e-c460f3c64170.png)

**Comment by jaderfeijo** [comment]
@johnrees I'm not sure I understand your question correctly. Are you trying to set your terminal theme/background colour to black, or only when you're using Vim?

**Comment by johnrees** [comment]
ah sorry i didn't phrase it very well. yes I just want everything in tmux to share the same dark theme like the screenshot (irb, $, vim...) e.g. base16-railscasts

https://raw.githubusercontent.com/chrishunt/dot-files/master/.screenshot.jpg

but my command prompt has a white bg

**Comment by jaderfeijo** [comment]
@johnrees If we're talking Terminal specific settings, you need to set your default theme to Homebrew or Pro. You can do that by selecting your desired theme and selecting the Default button at the bottom right of the Terminal Settings screen. You'll have to open a new window in order for your changes to take effect.

You might also need to set your New Window With Profile to your desired theme, as in the screenshot below:

![screen shot 2016-01-27 at 14 54 29](https://cloud.githubusercontent.com/assets/3536255/12617048/e2895064-c505-11e5-90ce-6b8afce77bb7.png)

**Comment by johnrees** [comment]
thanks for trying to help @jaderfeijo I get that. I'm doing a terrible job explaining what I mean here.

Say for example, I set my terminal profile to Pro.. whenever I am doing terminal, it uses Terminal's 'Pro' color scheme, but I want to share the same color scheme that I'm using in vim

### inconsistent colors I have
(bright terminal colors on the left, muted molokai theme colors on the right)

![screen shot 2016-01-27 at 15 17 25](https://cloud.githubusercontent.com/assets/601961/12617776/1588908a-c509-11e5-940e-f54c0d36774d.png)

### consistent colors I want
same theme colors in all tabs
![68747470733a2f2f7261772e6769746875622e636f6d2f636872697368756e742f636f6c6f722d736368656d65732f6d61737465722f7261696c7363617374732f73637265656e73686f742e706e67-1](https://cloud.githubusercontent.com/assets/601961/12617789/210317e6-c509-11e5-96a4-db889593896f.png)

I hope that makes sense, don't worry if not I'll close the 'issue' and try and figure it out myself

**Comment by johnrees** [comment]
I guess I need to install terminal-specific colorschemes that match vim's .vim colorscheme, I assumed it would be possible for terminal to somehow fetch its colors from the .vim colorschemes

**Comment by jaderfeijo** [comment]
@johnrees I see... now I understand what you're trying to accomplish. Yes, I'm afraid you'll have to create a colour theme for Terminal that matches your vim colour scheme.

An alternative perhaps would be switching to iTerm2, it provides many advanced features Terminal.app does not have. Maybe there is an easier way to accomplish what you're trying to do using iTerm.

**Comment by johnrees** [comment]
No worries. Thanks for your help, iTerm2 is getting me well on the way to where I wanted to be.

**Comment by chrishunt** [comment]
Hi @johnrees and thanks for jumping in @jaderfeijo!

It looks like you may want to checkout the color schemes repo:

https://github.com/chrishunt/color-schemes

There's a matching [iTerm color scheme](https://github.com/chrishunt/color-schemes/blob/master/railscasts/base16-railscasts-custom.dark.256.itermcolors) you can install and set.

<img width="680" alt="colors" src="https://cloud.githubusercontent.com/assets/65323/12699551/254c88e2-c774-11e5-9885-60a4754a7aef.png">
